apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: kustomize-

resources:
- resources/frontend-deployment.yaml
- resources/frontend-service.yaml

# images:
#   - name: jtrevinodev/guestbook
#     newName: jtrevinodev/guestbook
#     newTag: 
